### ISSUE TITLE
Read me minor issue

### ISSUE THREAD

**Issue by randyh0329** [datadudes/impala-rest-api#1]
```
docker run -e IMPALA_HOST=$YOUR_IMPALA_HOST_IP \
    -e SECURITY_TOKEN=$THE_TOKEN \
    -p $HOST_PORT:5000 \
    --name impala-api --link impala-api-redis:redis \
    -d datadudes/impala-rest-api:latest
```

```
curl -G 'http://$YOUR_DOCKER_HOST_IP:$HOST_PORT/impala?header=true&token=$THE_TOKEN' \
  --data-urlencode 'q=select * from customers limit 5' \
  --header 'Accept: text/csv'
```

Do not set `IMPALA_HOST` to `127.0.0.1 or localhost` , this will make python rest  api app to query localhost inside the container.  

Hope this can make step by step more helpful. :)

**Comment by DonDebonair** [comment]
I don't understand the issue. `IMPALA_HOST=$YOUR_HOST_IP` suggests that you should always use the IP of your Docker host as `IMPALA_HOST`, which is simply not true. `IMPALA_HOST` can be anything.
Of course you shouldn't point it to `localhost` when running inside a container.

Can you tell us what your actual suggestion is?

**Comment by randyh0329** [comment]
Oops, I'm not suggest using the `IMPALA_HOST` as the Docker host.
Sorry, I should write it clearly. 

Just suggest that if the step by step guide could 1. make the `port forward` in docker run command, 2. hint user that this application has different IP involved, and not confused the user whom is not familiar with docker. 

BTW, this docker is really helpful. Appreciated it.
